#!/usr/bin/env bash
# configures an Nginx server to listen on port 80.
# configure Nginx to listen on port 80 for all active IPv4 IPs
sudo ln -sf //etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
sudo service nginx restart
