#!/usr/bin/env bash
# remove the default Nginx configuration file
rm /etc/nginx/sites-available/default
# Configure Nginx to listen on port 80 for all active IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
